### ISSUE TITLE
fatal error: Audio.h: No such file or directory

### ISSUE THREAD

**Issue by machewww** [VolosR/mp3Waveshare185#1]
mp3Waveshare185-main\mp3Player\mp3Player.ino:2:10: fatal error: Audio.h: No such file or directory
    2 | #include "Audio.h"
      |          ^~~~~~~~~
compilation terminated.
exit status 1

Compilation error: Audio.h: No such file or directory

Trying to compile on W11/Arduino IDE 2.3.6. Is the Audio.h from another package?
